//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMS : DbContext
    {
      public IMS()
            : base("name=BASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BASE_Cities> BASE_Cities { get; set; }
        public DbSet<BASE_Concepts> BASE_Concepts { get; set; }
        public DbSet<BASE_Countries> BASE_Countries { get; set; }
        public DbSet<BASE_CurrencyTypes> BASE_CurrencyTypes { get; set; }
        public DbSet<BASE_Descriptions> BASE_Descriptions { get; set; }
        public DbSet<BASE_DocumentTypes> BASE_DocumentTypes { get; set; }
        public DbSet<BASE_Languages> BASE_Languages { get; set; }
        public DbSet<BASE_PostalCodes> BASE_PostalCodes { get; set; }
        public DbSet<BASE_Profiles> BASE_Profiles { get; set; }
        public DbSet<BASE_ProfilesResources> BASE_ProfilesResources { get; set; }
        public DbSet<BASE_Provinces> BASE_Provinces { get; set; }
        public DbSet<BASE_ReceiptTypes> BASE_ReceiptTypes { get; set; }
        public DbSet<BASE_Resources> BASE_Resources { get; set; }
        public DbSet<BASE_Taxes> BASE_Taxes { get; set; }
        public DbSet<BASE_Uom> BASE_Uom { get; set; }
        public DbSet<BASE_UserProfiles> BASE_UserProfiles { get; set; }
        public DbSet<BASE_Users> BASE_Users { get; set; }
    }
}
