//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_PostalCodes
    {
        public int postalCodeId { get; set; }
        public string cpNumber { get; set; }
        public int cityId { get; set; }
    
        public virtual BASE_Cities BASE_Cities { get; set; }
    }
}
