//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CurrencyTypes
    {
        public int currencyTypeId { get; set; }
        public string fiscalCurrencyTypeId { get; set; }
        public int tableKeyId { get; set; }
        public string abreviation { get; set; }
    }
}
