//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSEquipmentCapabilityTestSpecifications
    {
        public MES_MSEquipmentCapabilityTestSpecifications()
        {
            this.MES_MSTestedEquipmentClassProperties = new HashSet<MES_MSTestedEquipmentClassProperties>();
            this.MES_MSTestedEquipmentProperties = new HashSet<MES_MSTestedEquipmentProperties>();
        }
    
        public int equipmentCapabilitiyTestSpecificationId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string version { get; set; }
    
        public virtual ICollection<MES_MSTestedEquipmentClassProperties> MES_MSTestedEquipmentClassProperties { get; set; }
        public virtual ICollection<MES_MSTestedEquipmentProperties> MES_MSTestedEquipmentProperties { get; set; }
    }
}
