//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSTestedEquipmentClassProperties
    {
        public int testedEquipmentClassPropertyId { get; set; }
        public int equipmentClassId { get; set; }
        public int equipmentClassPropertyId { get; set; }
        public int equipmentCapabilitiyTestSpecificationId { get; set; }
    
        public virtual MES_MSEquipmentCapabilityTestSpecifications MES_MSEquipmentCapabilityTestSpecifications { get; set; }
        public virtual MES_MSEquipmentClasses MES_MSEquipmentClasses { get; set; }
        public virtual MES_MSEquipmentClassProperties MES_MSEquipmentClassProperties { get; set; }
    }
}
