//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSEquipments
    {
        public MES_MSEquipments()
        {
            this.MES_MSEquipmentClassEquipments = new HashSet<MES_MSEquipmentClassEquipments>();
            this.MES_MSEquipmentProperties = new HashSet<MES_MSEquipmentProperties>();
            this.MES_MSTestedEquipmentProperties = new HashSet<MES_MSTestedEquipmentProperties>();
        }
    
        public int equipmentId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<MES_MSEquipmentClassEquipments> MES_MSEquipmentClassEquipments { get; set; }
        public virtual ICollection<MES_MSEquipmentProperties> MES_MSEquipmentProperties { get; set; }
        public virtual ICollection<MES_MSTestedEquipmentProperties> MES_MSTestedEquipmentProperties { get; set; }
    }
}
