//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSEquipmentProperties
    {
        public MES_MSEquipmentProperties()
        {
            this.MES_MSTestedEquipmentProperties = new HashSet<MES_MSTestedEquipmentProperties>();
        }
    
        public int equipmentPropertyId { get; set; }
        public int equipmentId { get; set; }
        public int propertyId { get; set; }
        public int propertyValueId { get; set; }
    
        public virtual MES_MSEquipments MES_MSEquipments { get; set; }
        public virtual MES_MSProperties MES_MSProperties { get; set; }
        public virtual MES_MSPropertyValues MES_MSPropertyValues { get; set; }
        public virtual ICollection<MES_MSTestedEquipmentProperties> MES_MSTestedEquipmentProperties { get; set; }
    }
}
