//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSEquipmentClassProperties
    {
        public MES_MSEquipmentClassProperties()
        {
            this.MES_MSTestedEquipmentClassProperties = new HashSet<MES_MSTestedEquipmentClassProperties>();
        }
    
        public int equipmentClassPropertyId { get; set; }
        public int equipmentClassId { get; set; }
        public int propertyId { get; set; }
        public int propertyValueId { get; set; }
    
        public virtual MES_MSEquipmentClasses MES_MSEquipmentClasses { get; set; }
        public virtual MES_MSProperties MES_MSProperties { get; set; }
        public virtual MES_MSPropertyValues MES_MSPropertyValues { get; set; }
        public virtual ICollection<MES_MSTestedEquipmentClassProperties> MES_MSTestedEquipmentClassProperties { get; set; }
    }
}
