//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSEquipmentClassEquipments
    {
        public int equipmentClassEquipmentsId { get; set; }
        public int equipmentClassId { get; set; }
        public int equipmentId { get; set; }
    
        public virtual MES_MSEquipmentClasses MES_MSEquipmentClasses { get; set; }
        public virtual MES_MSEquipments MES_MSEquipments { get; set; }
    }
}
