//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSTestedEquipmentProperties
    {
        public int testedEquipmentPropertyId { get; set; }
        public int equipmentId { get; set; }
        public int equipmentPropertyId { get; set; }
        public int equipmentCapabilitiyTestSpecificationId { get; set; }
    
        public virtual MES_MSEquipmentCapabilityTestSpecifications MES_MSEquipmentCapabilityTestSpecifications { get; set; }
        public virtual MES_MSEquipmentProperties MES_MSEquipmentProperties { get; set; }
        public virtual MES_MSEquipments MES_MSEquipments { get; set; }
    }
}
