//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MES_MSEquipmentCapabilityTestSpecifications> MES_MSEquipmentCapabilityTestSpecifications { get; set; }
        public DbSet<MES_MSEquipmentClassEquipments> MES_MSEquipmentClassEquipments { get; set; }
        public DbSet<MES_MSEquipmentClasses> MES_MSEquipmentClasses { get; set; }
        public DbSet<MES_MSEquipmentClassProperties> MES_MSEquipmentClassProperties { get; set; }
        public DbSet<MES_MSEquipmentProperties> MES_MSEquipmentProperties { get; set; }
        public DbSet<MES_MSEquipments> MES_MSEquipments { get; set; }
        public DbSet<MES_MSProperties> MES_MSProperties { get; set; }
        public DbSet<MES_MSPropertyValues> MES_MSPropertyValues { get; set; }
        public DbSet<MES_MSTestedEquipmentClassProperties> MES_MSTestedEquipmentClassProperties { get; set; }
        public DbSet<MES_MSTestedEquipmentProperties> MES_MSTestedEquipmentProperties { get; set; }
    }
}
