//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFIP_TiposDocumento
    {
        public AFIP_TiposDocumento()
        {
            this.ERP_Clients = new HashSet<ERP_Clients>();
            this.ERP_Suppliers = new HashSet<ERP_Suppliers>();
        }
    
        public int codigoTipoDocumento { get; set; }
        public string name { get; set; }
        public int descriptionId { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual ICollection<ERP_Clients> ERP_Clients { get; set; }
        public virtual ICollection<ERP_Suppliers> ERP_Suppliers { get; set; }
    }
}
