//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFIP_Iva
    {
        public AFIP_Iva()
        {
            this.ERP_Invoices = new HashSet<ERP_Invoices>();
        }
    
        public int codigoIva { get; set; }
        public string name { get; set; }
        public int descriptionId { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual ICollection<ERP_Invoices> ERP_Invoices { get; set; }
    }
}
