//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFIP_UnidadesMedida
    {
        public AFIP_UnidadesMedida()
        {
            this.ERP_Articles = new HashSet<ERP_Articles>();
        }
    
        public int codigoUnidadMedida { get; set; }
        public int descriptionId { get; set; }
        public string abreviatura { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual ICollection<ERP_Articles> ERP_Articles { get; set; }
    }
}
