//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_Uom
    {
        public BASE_Uom()
        {
            this.BASE_Uom1 = new HashSet<BASE_Uom>();
        }
    
        public int uomId { get; set; }
        public string name { get; set; }
        public int descriptionId { get; set; }
        public string shortName { get; set; }
        public Nullable<int> baseUnitId { get; set; }
        public Nullable<decimal> baseUnitYield { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual ICollection<BASE_Uom> BASE_Uom1 { get; set; }
        public virtual BASE_Uom BASE_Uom2 { get; set; }
    }
}
