//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_Cities
    {
        public BASE_Cities()
        {
            this.BASE_PostalCodes = new HashSet<BASE_PostalCodes>();
            this.ERP_Addresses = new HashSet<ERP_Addresses>();
        }
    
        public int cityId { get; set; }
        public string name { get; set; }
        public int descriptionId { get; set; }
        public int provinceId { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual BASE_Provinces BASE_Provinces { get; set; }
        public virtual ICollection<BASE_PostalCodes> BASE_PostalCodes { get; set; }
        public virtual ICollection<ERP_Addresses> ERP_Addresses { get; set; }
    }
}
