//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_Descriptions
    {
        public BASE_Descriptions()
        {
            this.AFIP_ConceptosIncluidos = new HashSet<AFIP_ConceptosIncluidos>();
            this.AFIP_Iva = new HashSet<AFIP_Iva>();
            this.AFIP_TiposComprobante = new HashSet<AFIP_TiposComprobante>();
            this.AFIP_TiposDocumento = new HashSet<AFIP_TiposDocumento>();
            this.AFIP_TiposMonedas = new HashSet<AFIP_TiposMonedas>();
            this.AFIP_UnidadesMedida = new HashSet<AFIP_UnidadesMedida>();
            this.BASE_Cities = new HashSet<BASE_Cities>();
            this.BASE_Countries = new HashSet<BASE_Countries>();
            this.BASE_Profiles = new HashSet<BASE_Profiles>();
            this.BASE_Provinces = new HashSet<BASE_Provinces>();
            this.BASE_Uom = new HashSet<BASE_Uom>();
            this.ERP_Banks = new HashSet<ERP_Banks>();
            this.ERP_ContactTypes = new HashSet<ERP_ContactTypes>();
            this.ERP_Contracts = new HashSet<ERP_Contracts>();
            this.ERP_PaymentTypes = new HashSet<ERP_PaymentTypes>();
            this.ERP_SalesConditions = new HashSet<ERP_SalesConditions>();
            this.ERP_SalesOrderStates = new HashSet<ERP_SalesOrderStates>();
            this.ERP_ShippingNoteStates = new HashSet<ERP_ShippingNoteStates>();
        }
    
        public int descriptionId { get; set; }
        public int languageId { get; set; }
        public string descriptionText { get; set; }
    
        public virtual ICollection<AFIP_ConceptosIncluidos> AFIP_ConceptosIncluidos { get; set; }
        public virtual ICollection<AFIP_Iva> AFIP_Iva { get; set; }
        public virtual ICollection<AFIP_TiposComprobante> AFIP_TiposComprobante { get; set; }
        public virtual ICollection<AFIP_TiposDocumento> AFIP_TiposDocumento { get; set; }
        public virtual ICollection<AFIP_TiposMonedas> AFIP_TiposMonedas { get; set; }
        public virtual ICollection<AFIP_UnidadesMedida> AFIP_UnidadesMedida { get; set; }
        public virtual ICollection<BASE_Cities> BASE_Cities { get; set; }
        public virtual ICollection<BASE_Countries> BASE_Countries { get; set; }
        public virtual BASE_Languages BASE_Languages { get; set; }
        public virtual ICollection<BASE_Profiles> BASE_Profiles { get; set; }
        public virtual ICollection<BASE_Provinces> BASE_Provinces { get; set; }
        public virtual ICollection<BASE_Uom> BASE_Uom { get; set; }
        public virtual ICollection<ERP_Banks> ERP_Banks { get; set; }
        public virtual ICollection<ERP_ContactTypes> ERP_ContactTypes { get; set; }
        public virtual ICollection<ERP_Contracts> ERP_Contracts { get; set; }
        public virtual ICollection<ERP_PaymentTypes> ERP_PaymentTypes { get; set; }
        public virtual ICollection<ERP_SalesConditions> ERP_SalesConditions { get; set; }
        public virtual ICollection<ERP_SalesOrderStates> ERP_SalesOrderStates { get; set; }
        public virtual ICollection<ERP_ShippingNoteStates> ERP_ShippingNoteStates { get; set; }
    }
}
