//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_Profiles
    {
        public BASE_Profiles()
        {
            this.BASE_ProfilesResources = new HashSet<BASE_ProfilesResources>();
            this.BASE_UserProfiles = new HashSet<BASE_UserProfiles>();
        }
    
        public int profileId { get; set; }
        public string name { get; set; }
        public int descriptionId { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual ICollection<BASE_ProfilesResources> BASE_ProfilesResources { get; set; }
        public virtual ICollection<BASE_UserProfiles> BASE_UserProfiles { get; set; }
    }
}
