//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ContactTypes
    {
        public ERP_ContactTypes()
        {
            this.ERP_Contacts = new HashSet<ERP_Contacts>();
        }
    
        public int contactTypeId { get; set; }
        public string name { get; set; }
        public int tableKeyId { get; set; }
    
        public virtual ICollection<ERP_Contacts> ERP_Contacts { get; set; }
    }
}
