//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ItemsCreditNote
    {
        public int itemCreditNoteId { get; set; }
        public int creditNoteId { get; set; }
        public int shippingNoteId { get; set; }
        public int quantity { get; set; }
    
        public virtual ERP_CreditNote ERP_CreditNote { get; set; }
        public virtual ERP_ShippingNote ERP_ShippingNote { get; set; }
    }
}
