//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_SalesOrderStates
    {
        public ERP_SalesOrderStates()
        {
            this.ERP_SalesOrder = new HashSet<ERP_SalesOrder>();
        }
    
        public int salesOrderStateId { get; set; }
        public string name { get; set; }
        public int tableKeyId { get; set; }
    
        public virtual ICollection<ERP_SalesOrder> ERP_SalesOrder { get; set; }
    }
}
