//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_BankAccounts
    {
        public int bankAccountId { get; set; }
        public int bankId { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<int> companyId { get; set; }
        public string cbu { get; set; }
        public string accountNumber { get; set; }
        public string cbuAlias { get; set; }
    
        public virtual ERP_Banks ERP_Banks { get; set; }
        public virtual ERP_Clients ERP_Clients { get; set; }
        public virtual ERP_Companies ERP_Companies { get; set; }
        public virtual ERP_Suppliers ERP_Suppliers { get; set; }
    }
}
