//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_Invoices
    {
        public ERP_Invoices()
        {
            this.ERP_CreditNote = new HashSet<ERP_CreditNote>();
            this.ERP_Payments = new HashSet<ERP_Payments>();
            this.ERP_ShippingNotesInvoices = new HashSet<ERP_ShippingNotesInvoices>();
        }
    
        public int invoiceId { get; set; }
        public int pointOfSaleId { get; set; }
        public int invoiceNumber { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public int codigoTipoComprobante { get; set; }
        public int codigoTipoMoneda { get; set; }
        public int codigoConcepto { get; set; }
        public int codigoIva { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
        public string cae { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public int salesConditionId { get; set; }
        public Nullable<decimal> changeRate { get; set; }
    
        public virtual AFIP_ConceptosIncluidos AFIP_ConceptosIncluidos { get; set; }
        public virtual AFIP_Iva AFIP_Iva { get; set; }
        public virtual AFIP_TiposComprobante AFIP_TiposComprobante { get; set; }
        public virtual AFIP_TiposMonedas AFIP_TiposMonedas { get; set; }
        public virtual ICollection<ERP_CreditNote> ERP_CreditNote { get; set; }
        public virtual ERP_SalesConditions ERP_SalesConditions { get; set; }
        public virtual ERP_PointsOfSales ERP_PointsOfSales { get; set; }
        public virtual ICollection<ERP_Payments> ERP_Payments { get; set; }
        public virtual ICollection<ERP_ShippingNotesInvoices> ERP_ShippingNotesInvoices { get; set; }
    }
}
