//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_PriceArticlesHistory
    {
        public int priceArticlesHistoryId { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public decimal price { get; set; }
        public int articleId { get; set; }
        public int receiptTypeId { get; set; }
    
        public virtual ERP_Articles ERP_Articles { get; set; }
    }
}
