//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ItemsContract
    {
        public int itemsContractId { get; set; }
        public int contractId { get; set; }
        public int articleId { get; set; }
        public decimal price { get; set; }
        public int position { get; set; }
        public int codigoTipoMoneda { get; set; }
    
        public virtual AFIP_TiposMonedas AFIP_TiposMonedas { get; set; }
        public virtual ERP_Articles ERP_Articles { get; set; }
        public virtual ERP_Contracts ERP_Contracts { get; set; }
    }
}
