//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ShippingNoteStates
    {
        public ERP_ShippingNoteStates()
        {
            this.ERP_ShippingNote = new HashSet<ERP_ShippingNote>();
        }
    
        public int shippingNoteStateId { get; set; }
        public string name { get; set; }
        public int descriptionId { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual ICollection<ERP_ShippingNote> ERP_ShippingNote { get; set; }
    }
}
