//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_Banks
    {
        public ERP_Banks()
        {
            this.ERP_BankAccounts = new HashSet<ERP_BankAccounts>();
            this.ERP_BankRelations = new HashSet<ERP_BankRelations>();
        }
    
        public int bankId { get; set; }
        public string name { get; set; }
        public int descriptionId { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual ICollection<ERP_BankAccounts> ERP_BankAccounts { get; set; }
        public virtual ICollection<ERP_BankRelations> ERP_BankRelations { get; set; }
    }
}
