//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ArticlesCustomer
    {
        public int articleCustomerd { get; set; }
        public int articleId { get; set; }
        public int personId { get; set; }
        public int personTypeId { get; set; }
        public string customerArticleCode { get; set; }
    
        public virtual ERP_Articles ERP_Articles { get; set; }
    }
}
