//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ItemsShippingNote
    {
        public int itemShippingNoteId { get; set; }
        public int shippingNoteId { get; set; }
        public int itemsSalesOrderId { get; set; }
        public int quantity { get; set; }
        public Nullable<int> articleSupplierId { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual ERP_ArticlesSupplier ERP_ArticlesSupplier { get; set; }
        public virtual ERP_ItemsSalesOrder ERP_ItemsSalesOrder { get; set; }
        public virtual ERP_ShippingNote ERP_ShippingNote { get; set; }
    }
}
