//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ArticleSupplierCostHistory
    {
        public int articleSupplierPriceHistoryId { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public decimal cost { get; set; }
        public int articleSupplierId { get; set; }
        public int codigoTipoMoneda { get; set; }
    
        public virtual ERP_ArticlesSupplier ERP_ArticlesSupplier { get; set; }
    }
}
