//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ItemsSalesOrder
    {
        public ERP_ItemsSalesOrder()
        {
            this.ERP_ItemsShippingNote = new HashSet<ERP_ItemsShippingNote>();
        }
    
        public int itemsSalesOrderId { get; set; }
        public int articleId { get; set; }
        public int salesOrderId { get; set; }
        public int quantity { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public Nullable<decimal> price { get; set; }
        public int position { get; set; }
    
        public virtual ERP_Articles ERP_Articles { get; set; }
        public virtual ERP_SalesOrder ERP_SalesOrder { get; set; }
        public virtual ICollection<ERP_ItemsShippingNote> ERP_ItemsShippingNote { get; set; }
    }
}
