//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ShippingNote
    {
        public ERP_ShippingNote()
        {
            this.ERP_ItemsCreditNote = new HashSet<ERP_ItemsCreditNote>();
            this.ERP_ItemsShippingNote = new HashSet<ERP_ItemsShippingNote>();
            this.ERP_ShippingNotesInvoices = new HashSet<ERP_ShippingNotesInvoices>();
        }
    
        public int shippingNoteId { get; set; }
        public System.DateTime releaseDate { get; set; }
        public Nullable<int> shippingNoteNumber { get; set; }
        public int shippingNoteStateId { get; set; }
        public string observations { get; set; }
        public int salesOrderId { get; set; }
        public Nullable<int> transportId { get; set; }
        public Nullable<int> addressId { get; set; }
        public string cai { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<int> pointOfSalesId { get; set; }
    
        public virtual ERP_Addresses ERP_Addresses { get; set; }
        public virtual ICollection<ERP_ItemsCreditNote> ERP_ItemsCreditNote { get; set; }
        public virtual ICollection<ERP_ItemsShippingNote> ERP_ItemsShippingNote { get; set; }
        public virtual ERP_PointsOfSales ERP_PointsOfSales { get; set; }
        public virtual ERP_ShippingNoteStates ERP_ShippingNoteStates { get; set; }
        public virtual ICollection<ERP_ShippingNotesInvoices> ERP_ShippingNotesInvoices { get; set; }
    }
}
