//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_Payments
    {
        public int paymentId { get; set; }
        public int invoiceId { get; set; }
        public int paymentTypesId { get; set; }
        public decimal amount { get; set; }
    
        public virtual ERP_Invoices ERP_Invoices { get; set; }
        public virtual ERP_PaymentTypes ERP_PaymentTypes { get; set; }
    }
}
