//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_Contracts
    {
        public ERP_Contracts()
        {
            this.ERP_ItemsContract = new HashSet<ERP_ItemsContract>();
            this.ERP_SalesOrder = new HashSet<ERP_SalesOrder>();
        }
    
        public int contractId { get; set; }
        public int clientId { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public int descriptionId { get; set; }
        public string clientBuyerName { get; set; }
    
        public virtual BASE_Descriptions BASE_Descriptions { get; set; }
        public virtual ERP_Clients ERP_Clients { get; set; }
        public virtual ICollection<ERP_ItemsContract> ERP_ItemsContract { get; set; }
        public virtual ICollection<ERP_SalesOrder> ERP_SalesOrder { get; set; }
    }
}
