//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ArticlesClient
    {
        public int articleClientId { get; set; }
        public int articleId { get; set; }
        public int clientId { get; set; }
        public string clientArticleCode { get; set; }
    
        public virtual ERP_Articles ERP_Articles { get; set; }
        public virtual ERP_Clients ERP_Clients { get; set; }
    }
}
