//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMS : DbContext
    {
        public IMS()
            : base("name=IMS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AFIP_ConceptosIncluidos> AFIP_ConceptosIncluidos { get; set; }
        public DbSet<AFIP_Iva> AFIP_Iva { get; set; }
        public DbSet<AFIP_TiposComprobante> AFIP_TiposComprobante { get; set; }
        public DbSet<AFIP_TiposDocumento> AFIP_TiposDocumento { get; set; }
        public DbSet<AFIP_TiposMonedas> AFIP_TiposMonedas { get; set; }
        public DbSet<AFIP_UnidadesMedida> AFIP_UnidadesMedida { get; set; }
        public DbSet<BASE_Cities> BASE_Cities { get; set; }
        public DbSet<BASE_Countries> BASE_Countries { get; set; }
        public DbSet<BASE_Descriptions> BASE_Descriptions { get; set; }
        public DbSet<BASE_Languages> BASE_Languages { get; set; }
        public DbSet<BASE_PostalCodes> BASE_PostalCodes { get; set; }
        public DbSet<BASE_Profiles> BASE_Profiles { get; set; }
        public DbSet<BASE_ProfilesResources> BASE_ProfilesResources { get; set; }
        public DbSet<BASE_Provinces> BASE_Provinces { get; set; }
        public DbSet<BASE_Resources> BASE_Resources { get; set; }
        public DbSet<BASE_Uom> BASE_Uom { get; set; }
        public DbSet<BASE_UserProfiles> BASE_UserProfiles { get; set; }
        public DbSet<BASE_Users> BASE_Users { get; set; }
        public DbSet<ERP_Addresses> ERP_Addresses { get; set; }
        public DbSet<ERP_Articles> ERP_Articles { get; set; }
        public DbSet<ERP_ArticlesClient> ERP_ArticlesClient { get; set; }
        public DbSet<ERP_ArticlesSupplier> ERP_ArticlesSupplier { get; set; }
        public DbSet<ERP_ArticleSupplierCostHistory> ERP_ArticleSupplierCostHistory { get; set; }
        public DbSet<ERP_BankAccounts> ERP_BankAccounts { get; set; }
        public DbSet<ERP_BankRelations> ERP_BankRelations { get; set; }
        public DbSet<ERP_Banks> ERP_Banks { get; set; }
        public DbSet<ERP_Clients> ERP_Clients { get; set; }
        public DbSet<ERP_Companies> ERP_Companies { get; set; }
        public DbSet<ERP_Contacts> ERP_Contacts { get; set; }
        public DbSet<ERP_ContactTypes> ERP_ContactTypes { get; set; }
        public DbSet<ERP_Contracts> ERP_Contracts { get; set; }
        public DbSet<ERP_CreditNote> ERP_CreditNote { get; set; }
        public DbSet<ERP_Invoices> ERP_Invoices { get; set; }
        public DbSet<ERP_ItemsContract> ERP_ItemsContract { get; set; }
        public DbSet<ERP_ItemsCreditNote> ERP_ItemsCreditNote { get; set; }
        public DbSet<ERP_ItemsSalesOrder> ERP_ItemsSalesOrder { get; set; }
        public DbSet<ERP_ItemsShippingNote> ERP_ItemsShippingNote { get; set; }
        public DbSet<ERP_Payments> ERP_Payments { get; set; }
        public DbSet<ERP_PaymentTypes> ERP_PaymentTypes { get; set; }
        public DbSet<ERP_PointsOfSales> ERP_PointsOfSales { get; set; }
        public DbSet<ERP_PriceArticlesHistory> ERP_PriceArticlesHistory { get; set; }
        public DbSet<ERP_SalesConditions> ERP_SalesConditions { get; set; }
        public DbSet<ERP_SalesOrder> ERP_SalesOrder { get; set; }
        public DbSet<ERP_SalesOrderStates> ERP_SalesOrderStates { get; set; }
        public DbSet<ERP_ShippingNote> ERP_ShippingNote { get; set; }
        public DbSet<ERP_ShippingNotesInvoices> ERP_ShippingNotesInvoices { get; set; }
        public DbSet<ERP_ShippingNoteStates> ERP_ShippingNoteStates { get; set; }
        public DbSet<ERP_Suppliers> ERP_Suppliers { get; set; }
        public DbSet<RPT_Reports> RPT_Reports { get; set; }
        public DbSet<RPT_ReportsPointOfSales> RPT_ReportsPointOfSales { get; set; }
    }
}
