//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMS : DbContext
    {
        public IMS()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ERP_Addresses> ERP_Addresses { get; set; }
        public DbSet<ERP_Articles> ERP_Articles { get; set; }
        public DbSet<ERP_ArticlesCustomer> ERP_ArticlesCustomer { get; set; }
        public DbSet<ERP_ArticlesSupplier> ERP_ArticlesSupplier { get; set; }
        public DbSet<ERP_ArticleSupplierCostHistory> ERP_ArticleSupplierCostHistory { get; set; }
        public DbSet<ERP_BankAccounts> ERP_BankAccounts { get; set; }
        public DbSet<ERP_Banks> ERP_Banks { get; set; }
        public DbSet<ERP_Contacts> ERP_Contacts { get; set; }
        public DbSet<ERP_ContactTypes> ERP_ContactTypes { get; set; }
        public DbSet<ERP_Contracts> ERP_Contracts { get; set; }
        public DbSet<ERP_CreditNote> ERP_CreditNote { get; set; }
        public DbSet<ERP_Invoices> ERP_Invoices { get; set; }
        public DbSet<ERP_ItemsContract> ERP_ItemsContract { get; set; }
        public DbSet<ERP_ItemsCreditNote> ERP_ItemsCreditNote { get; set; }
        public DbSet<ERP_ItemsSalesOrder> ERP_ItemsSalesOrder { get; set; }
        public DbSet<ERP_ItemsShippingNote> ERP_ItemsShippingNote { get; set; }
        public DbSet<ERP_Payments> ERP_Payments { get; set; }
        public DbSet<ERP_PaymentTypes> ERP_PaymentTypes { get; set; }
        public DbSet<ERP_Persons> ERP_Persons { get; set; }
        public DbSet<ERP_PersonTypes> ERP_PersonTypes { get; set; }
        public DbSet<ERP_PointsOfSales> ERP_PointsOfSales { get; set; }
        public DbSet<ERP_PriceArticlesHistory> ERP_PriceArticlesHistory { get; set; }
        public DbSet<ERP_SalesConditions> ERP_SalesConditions { get; set; }
        public DbSet<ERP_SalesOrder> ERP_SalesOrder { get; set; }
        public DbSet<ERP_SalesOrderStates> ERP_SalesOrderStates { get; set; }
        public DbSet<ERP_ShippingNote> ERP_ShippingNote { get; set; }
        public DbSet<ERP_ShippingNotesInvoices> ERP_ShippingNotesInvoices { get; set; }
        public DbSet<ERP_ShippingNoteStates> ERP_ShippingNoteStates { get; set; }
    }
}
