//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_ReportsPointOfSales
    {
        public int reportPointsOfSalesId { get; set; }
        public int reportId { get; set; }
        public int pointsOfSalesId { get; set; }
    
        public virtual ERP_PointsOfSales ERP_PointsOfSales { get; set; }
        public virtual RPT_Reports RPT_Reports { get; set; }
    }
}
