//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_Reports
    {
        public RPT_Reports()
        {
            this.RPT_ReportsPointOfSales = new HashSet<RPT_ReportsPointOfSales>();
        }
    
        public int reportId { get; set; }
        public string name { get; set; }
        public string pathReport1 { get; set; }
        public string pathReport2 { get; set; }
        public string pathReport3 { get; set; }
    
        public virtual ICollection<RPT_ReportsPointOfSales> RPT_ReportsPointOfSales { get; set; }
    }
}
